CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE transaksi (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama_crypto VARCHAR(50) NOT NULL,
    jumlah DOUBLE NOT NULL,
    harga DOUBLE NOT NULL,
    tanggal DATE NOT NULL
);
